// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace WarehouseStockPredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("ItemId"), LoadColumn(0)]
        public string ItemId { get; set; }


        [ColumnName("LocationCode"), LoadColumn(1)]
        public float LocationCode { get; set; }


        [ColumnName("InQty"), LoadColumn(2)]
        public float InQty { get; set; }


        [ColumnName("OutQty"), LoadColumn(3)]
        public float OutQty { get; set; }


        [ColumnName("ItemType"), LoadColumn(4)]
        public string ItemType { get; set; }


        [ColumnName("TotalStockQty"), LoadColumn(5)]
        public float TotalStockQty { get; set; }


    }
}
